CREATE TABLE trips (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	code VARCHAR(14) NOT NULL,
	name VARCHAR(100) NOT NULL,
	duration_days INTEGER NOT NULL,
	start_date DATE NOT NULL,
	resort VARCHAR(150) NOT NULL,
	price_per_person NUMERIC(10, 2) NOT NULL,
	image_name VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,

	CONSTRAINT pk_trips PRIMARY KEY (id),
	CONSTRAINT uk_trips_code UNIQUE (code),

	CONSTRAINT ck_trips_code_format
		CHECK (code ~ '^[A-Z]{6}[0-9]{8}$'),

	CONSTRAINT ck_trips_name_not_blank
		CHECK (length(btrim(name)) > 0),

	CONSTRAINT ck_trips_duration_days
		CHECK (duration_days BETWEEN 1 AND 30),

	CONSTRAINT ck_trips_resort_not_blank
		CHECK (length(btrim(resort)) > 0),

	CONSTRAINT ck_trips_price_per_person
		CHECK (price_per_person > 0),

	CONSTRAINT ck_trips_image_name_format
		CHECK (image_name ~ '^[A-Za-z0-9_-]+\.(jpg|jpeg|png|webp)$'),

	CONSTRAINT ck_trips_description_not_blank
		CHECK (length(btrim(description)) > 0)
);

CREATE INDEX idx_trips_name ON trips (name);
CREATE INDEX idx_trips_resort ON trips (resort);
CREATE INDEX idx_trips_start_date ON trips (start_date);
CREATE INDEX idx_trips_code_upper ON trips (upper(code));